### ISSUE TITLE
Problem in plot_easy_example

### ISSUE THREAD

**Issue by RianneSchouten** [RianneSchouten/pymice#24]
WARNING: C:\Users\20200059\Documents\Github\pyampute\examples\plot_easy_example.py failed to execute correctly: Traceback (most recent call last):
  File "C:\Users\20200059\Documents\Github\pyampute\examples\plot_easy_example.py", line 86, in <module>
    X_imp_test = pipe.transform(X_compl_test)
  File "c:\users\20200059\appdata\local\programs\python\python38\lib\site-packages\sklearn\pipeline.py", line 549, in _transform
    Xt = transform.transform(Xt)
  File "C:\Users\20200059\Documents\Github\pyampute\pyampute\ampute.py", line 895, in transform
    chosen_candidates = np.random.binomial(
  File "mtrand.pyx", line 3373, in numpy.random.mtrand.RandomState.binomial
  File "__init__.pxd", line 749, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape

**Comment by davzaman** [comment]
Solved with 7518d8c see #26 for more
