### ISSUE TITLE
num_samples addressed before assigning variable

### ISSUE THREAD

**Issue by prabhant** [RianneSchouten/pymice#4]
Code

```
import numpy as np
from pymice.amputation.ampute import MultivariateAmputation

X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
X = np.asarray(X)
amp = MultivariateAmputation()
amp.fit_transform(X)
```

Error:
```
>>> amp.fit_transform(X)
2022-01-23 19:04:42,543 [INFO] No patterns passed, setting default pattern.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/prabhant/OpenML/pymice/pymice/amputation/ampute.py", line 807, in fit_transform
    X = self._validate_input(X)
  File "/Users/prabhant/OpenML/pymice/pymice/amputation/ampute.py", line 690, in _validate_input
    if len(self.patterns) / self.num_samples >= 0.7:
AttributeError: 'MultivariateAmputation' object has no attribute 'num_samples'
```
Looks like num_samples is addressed in here
[        self.num_samples = X.shape[0]](https://github.com/RianneSchouten/pymice/blob/c12c7ce93a6296b6d9b397a656a93273464464e9/pymice/amputation/ampute.py#L722)

**Comment by davzaman** [comment]
this should be fixed with ad3df532f1e83455ee02b25c0ea3ffa22841de2d
